/*
Generated by code-generator, do not edit it
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VpcConnectionListerExpansion allows custom methods to be added to
// VpcConnectionLister.
type VpcConnectionListerExpansion interface{}
