/*
Generated by code-generator, do not edit it
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	networkv1alpha1 "github.com/lucheng0127/bmsVpcGateway/pkg/apis/network/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VpcConnectionLister helps list VpcConnections.
// All objects returned here must be treated as read-only.
type VpcConnectionLister interface {
	// List lists all VpcConnections in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkv1alpha1.VpcConnection, err error)
	// Get retrieves the VpcConnection from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkv1alpha1.VpcConnection, error)
	VpcConnectionListerExpansion
}

// vpcConnectionLister implements the VpcConnectionLister interface.
type vpcConnectionLister struct {
	listers.ResourceIndexer[*networkv1alpha1.VpcConnection]
}

// NewVpcConnectionLister returns a new VpcConnectionLister.
func NewVpcConnectionLister(indexer cache.Indexer) VpcConnectionLister {
	return &vpcConnectionLister{listers.New[*networkv1alpha1.VpcConnection](indexer, networkv1alpha1.Resource("vpcconnection"))}
}
