/*
Generated by code-generator, do not edit it
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	networkv1alpha1 "github.com/lucheng0127/bmsVpcGateway/pkg/apis/network/v1alpha1"
	scheme "github.com/lucheng0127/bmsVpcGateway/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpcConnectionsGetter has a method to return a VpcConnectionInterface.
// A group's client should implement this interface.
type VpcConnectionsGetter interface {
	VpcConnections() VpcConnectionInterface
}

// VpcConnectionInterface has methods to work with VpcConnection resources.
type VpcConnectionInterface interface {
	Create(ctx context.Context, vpcConnection *networkv1alpha1.VpcConnection, opts v1.CreateOptions) (*networkv1alpha1.VpcConnection, error)
	Update(ctx context.Context, vpcConnection *networkv1alpha1.VpcConnection, opts v1.UpdateOptions) (*networkv1alpha1.VpcConnection, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpcConnection *networkv1alpha1.VpcConnection, opts v1.UpdateOptions) (*networkv1alpha1.VpcConnection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkv1alpha1.VpcConnection, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkv1alpha1.VpcConnectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkv1alpha1.VpcConnection, err error)
	VpcConnectionExpansion
}

// vpcConnections implements VpcConnectionInterface
type vpcConnections struct {
	*gentype.ClientWithList[*networkv1alpha1.VpcConnection, *networkv1alpha1.VpcConnectionList]
}

// newVpcConnections returns a VpcConnections
func newVpcConnections(c *NetworkV1alpha1Client) *vpcConnections {
	return &vpcConnections{
		gentype.NewClientWithList[*networkv1alpha1.VpcConnection, *networkv1alpha1.VpcConnectionList](
			"vpcconnections",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *networkv1alpha1.VpcConnection { return &networkv1alpha1.VpcConnection{} },
			func() *networkv1alpha1.VpcConnectionList { return &networkv1alpha1.VpcConnectionList{} },
		),
	}
}
