/*
Generated by code-generator, do not edit it
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/lucheng0127/bmsVpcGateway/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VpcConnections returns a VpcConnectionInformer.
	VpcConnections() VpcConnectionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VpcConnections returns a VpcConnectionInformer.
func (v *version) VpcConnections() VpcConnectionInformer {
	return &vpcConnectionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
